### ISSUE TITLE
Add an options page

### ISSUE THREAD

**Issue by techboyg5** [fxsitecompat/firefox-extension#2]
The options page should look like this:
`Options`
`[x] Show the News tab`
`[x] Show the Checker tab`
`[x] Show the Reporter tab`
`[x] Show the About tab`
`[x] Show the Compatibility tab in Inspector`
`Reset to Default`

Changes should be applied automatically. The "Reset to Default" button should reset to everything being checked.

**Comment by kyoshino** [comment]
Hi @techboyg5, thanks for the feedback! I don’t think the extension needs such options because there are only a few tabs, and these tabs are all about compatibility. In the future, I’ll strengthen ties among these tabs. For example, it could allow reporting issues directly from the Checker tab or checking issues directly from one of the News items.

DevTools itself has similar options, because it offers many different kinds of panels.

**Comment by kyoshino** [comment]
The About tab may seem redundant, but we need this so people understand it’s a third-party extension provided by an independent project. We could add a donation button or whatever.

**Comment by kyoshino** [comment]
The Inspector tabs probably have to be customizable, but that’s an issue of DevTools, not us. For example, the Animations tab may also be irrelevant to some of us. Feel free to file a bug to Mozilla’s Bugzilla.
